Check roll back (#43)
* Check roll back

* Add build process

diff --git a/.github/workflows/tag-on-merge.yml b/.github/workflows/tag-on-merge.yml
--- a/.github/workflows/tag-on-merge.yml
+++ b/.github/workflows/tag-on-merge.yml
@@ -33,8 +33,8 @@ jobs:
     steps:
       - name: Simulate_Run_Test
         run: |
-          echo "Test case Success"
-          exit 0
+          echo "Test case failed"
+          exit 1
         
   RollBack_on_Failure:
     runs-on: ubuntu-latest
@@ -52,6 +52,26 @@ jobs:
           PREVIOUS_TAG=$(git describe --tags $(git rev-list --tags --max-count=1 | tail -n 1))
           git checkout $PREVIOUS_TAG
           echo "Previous tag is $PREVIOUS_TAG"
+          sleep 5
+
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 16
+          cache: 'yarn'
+
+      - name: Create env file
+        run: |
+          touch .env
+          echo REACT_APP_FIREBASE_API_KEY=${{ secrets.API_KEY }} >> .env
+          echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
+          echo REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
+          echo REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
+          echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
+          echo REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> .env
+          
+      - run: yarn install
+
+      - run: yarn build
 
       - name: Perform Rollback
         uses: FirebaseExtended/action-hosting-deploy@v0
@@ -70,9 +90,7 @@ jobs:
       contents: write
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-            fetch-depth: '0'
+        uses: actions/checkout@v4
 
       - name: Bump version and push tag
         uses: anothrNick/github-tag-action@1.64.0
