test check only

diff --git a/.github/workflows/tag-on-merge.yml b/.github/workflows/tag-on-merge.yml
--- a/.github/workflows/tag-on-merge.yml
+++ b/.github/workflows/tag-on-merge.yml
@@ -1,45 +1,45 @@
 name: Create Tag on Merge to Main from develop branch
 on: pull_request
 jobs:
-  Deploy:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16
-          cache: 'yarn'
-      - name: Create env file
-        run: |
-          touch .env
-          echo REACT_APP_FIREBASE_API_KEY=${{ secrets.API_KEY }} >> .env
-          echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
-          echo REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
-          echo REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
-          echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
-          echo REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> .env
-      - run: yarn install
-      - run: yarn build
-      - uses: FirebaseExtended/action-hosting-deploy@v0
-        with:
-          repoToken: '${{ secrets.GITHUB_TOKEN }}'
-          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOYTEST_8048D }}'
-          projectId: deploytest-8048d
-          channelId: live
-          firebaseToolsVersion: 12.9.1
-  Simulate_Test:
-    runs-on: ubuntu-latest
-    needs: Deploy
-    steps:
-      - name: TestCase failed
-        run: |
-          echo "Test case failed"
-          exit 1
+  # Deploy:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16
+  #         cache: 'yarn'
+  #     - name: Create env file
+  #       run: |
+  #         touch .env
+  #         echo REACT_APP_FIREBASE_API_KEY=${{ secrets.API_KEY }} >> .env
+  #         echo REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
+  #         echo REACT_APP_FIREBASE_DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
+  #         echo REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
+  #         echo REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} >> .env
+  #         echo REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} >> .env
+  #     - run: yarn install
+  #     - run: yarn build
+  #     - uses: FirebaseExtended/action-hosting-deploy@v0
+  #       with:
+  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
+  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEPLOYTEST_8048D }}'
+  #         projectId: deploytest-8048d
+  #         channelId: live
+  #         firebaseToolsVersion: 12.9.1
+  # Simulate_Test:
+  #   runs-on: ubuntu-latest
+  #   needs: Deploy
+  #   steps:
+  #     - name: TestCase failed
+  #       run: |
+  #         echo "Test case failed"
+  #         exit 1
         
   RollBack_on_Failure:
     runs-on: ubuntu-latest
     needs: Simulate_Test
-    if: ${{ failure() }}
+    # if: ${{ failure() }}
     steps:
       - uses: actions/checkout@v4
         with: 
@@ -49,22 +49,22 @@ jobs:
         run: |
           echo "Rollback"
     
-  Create_Tag_on_Deploy:
-    runs-on: ubuntu-latest
-    needs: Simulate_Test
-    if: ${{ success() }}
-    permissions:
-      contents: write
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-            fetch-depth: '0'
+  # Create_Tag_on_Deploy:
+  #   runs-on: ubuntu-latest
+  #   needs: Simulate_Test
+  #   if: ${{ success() }}
+  #   permissions:
+  #     contents: write
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v2
+  #       with:
+  #           fetch-depth: '0'
 
-      - name: Bump version and push tag
-        uses: anothrNick/github-tag-action@1.64.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
-          WITH_V: true
-          DEFAULT_BRANCH: develop
-          RELEASE_BRANCHES: main
+  #     - name: Bump version and push tag
+  #       uses: anothrNick/github-tag-action@1.64.0
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+  #         WITH_V: true
+  #         DEFAULT_BRANCH: develop
+  #         RELEASE_BRANCHES: main
