Add roll back

diff --git a/.github/workflows/tag-on-merge.yml b/.github/workflows/tag-on-merge.yml
--- a/.github/workflows/tag-on-merge.yml
+++ b/.github/workflows/tag-on-merge.yml
@@ -27,9 +27,28 @@ jobs:
           projectId: deploytest-8048d
           channelId: live
           firebaseToolsVersion: 12.9.1
-  Create_Tag_on_Deploy:
+  Simulate_Test:
     runs-on: ubuntu-latest
     needs: Deploy
+    steps:
+      -name: TestCase failed
+      run: |
+        echo "Test case failed"
+        exit 1
+        
+  RollBack_on_Failure:
+    runs-on: ubuntu-latest
+    needs: Simulate_Test
+    if: ${{ failure() }}
+    steps:
+      -name: Rollback
+      run: |
+        echo "Rollback"
+    
+  Create_Tag_on_Deploy:
+    runs-on: ubuntu-latest
+    needs: Simulate_Test
+    if: ${{ success() }}
     permissions:
       contents: write
     steps:
