Check roll back

diff --git a/.github/workflows/tag-on-merge.yml b/.github/workflows/tag-on-merge.yml
--- a/.github/workflows/tag-on-merge.yml
+++ b/.github/workflows/tag-on-merge.yml
@@ -33,8 +33,8 @@ jobs:
     steps:
       - name: Simulate_Run_Test
         run: |
-          echo "Test case Success"
-          exit 0
+          echo "Test case failed"
+          exit 1
         
   RollBack_on_Failure:
     runs-on: ubuntu-latest
@@ -52,6 +52,7 @@ jobs:
           PREVIOUS_TAG=$(git describe --tags $(git rev-list --tags --max-count=1 | tail -n 1))
           git checkout $PREVIOUS_TAG
           echo "Previous tag is $PREVIOUS_TAG"
+          sleep 5
 
       - name: Perform Rollback
         uses: FirebaseExtended/action-hosting-deploy@v0
@@ -70,9 +71,7 @@ jobs:
       contents: write
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-            fetch-depth: '0'
+        uses: actions/checkout@v4
 
       - name: Bump version and push tag
         uses: anothrNick/github-tag-action@1.64.0
